# config.py
GEMINI_API_KEY = "AIzaSyD4RbrByWZV7LQGdxvexF3SjxYWGFgrQS8"   # Replace with your key
ACCESS_TOKEN = "EAAX3zeKfwksBPZAJcYyZCGFIZCmwErDmDxsvtcxfRNal577LQdaAu0VEhFkIOgbKErZBe7F4oUkiMLKT1IrlVaJ4IXCnKd5HUBIVZBvyXPXagpAjx3tPf4mupeHP0nmSLInKPSZBVZBWN3mwp9YKUZCLqsFQrsRLMjQrBEs6VH3MIW1lWZBQztA8Q9bJNIAOTKHmmFQZDZD"  # Permanent token from Meta
PHONE_NUMBER_ID = "782792474922761"     # From WhatsApp setup
